server:
  port: 8081

spring:
  application:
    name: securebank-api

  datasource:
    url: jdbc:mysql://localhost:3307/securebank?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: securebank123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/securebank
          jwk-set-uri: http://localhost:8181/realms/securebank/protocol/openid-connect/certs

springdoc:
    swagger-ui:
      path: /swagger-ui.html
      tags-sorter: alpha
    api-docs:
      path: /api-docs